# Generated by Django 2.2.7 on 2019-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField(blank=True, default='')),
                ('annotated', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, default='')),
            ],
        ),
    ]
